// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/speakup-variants/BoldPremium.tsx": () => import("../components/mockups/speakup-variants/BoldPremium.tsx"),
  "./components/mockups/speakup-variants/CleanLight.tsx": () => import("../components/mockups/speakup-variants/CleanLight.tsx"),
  "./components/mockups/speakup-variants/RefinedGlass.tsx": () => import("../components/mockups/speakup-variants/RefinedGlass.tsx")
};
